# This tells Spring Boot to use H2 (In-Memory Database)
#spring.datasource.url=jdbc:h2:mem:amazondb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=


server.port=8081
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/cafe_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mac@2026


# Hibernate Settings
# This tells Spring to create the table based on your @Entity class
spring.jpa.hibernate.ddl-auto=update
# This is the "Magic" line: It tells Spring to show you the SQL it writes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# expose all actuator endpoints
management.endpoints.web.exposure.include=*

# show full health details
management.endpoint.health.show-details=always

# custom app info (shows in /actuator/info)
info.app.name=Minicoy Cafe
info.app.description=Cafe Management System
info.app.version=1.0.0
info.app.developer=Divya