# This tells Spring Boot to use H2 (In-Memory Database)
#spring.datasource.url=jdbc:h2:mem:amazondb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=


server.port=8081
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/cafe_db?createDatabaseIfNotExist=true
spring.datasource.username=${db-username}
spring.datasource.password=${db-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Hibernate Settings
# This tells Spring to create the table based on your @Entity class
spring.jpa.hibernate.ddl-auto=validate
# This is the "Magic" line: It tells Spring to show you the SQL it writes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

#ACTUATOR
# expose all actuator endpoints
management.endpoints.web.exposure.include=*
# show full health details
management.endpoint.health.show-details=always

# custom app info (shows in /actuator/info)
info.app.name=Minicoy Cafe
info.app.description=Cafe Management System
info.app.version=1.0.0
info.app.developer=Divya

# JWT reads from Vault!
jwt.secret=${jwt-secret}
jwt.expiration=${jwt-expiration}

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html

# disable compatibility check
spring.cloud.compatibility-verifier.enabled=false